# Generated by Django 4.0.3 on 2022-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='admin-profile-image/')),
                ('admin_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=14)),
                ('email_address', models.CharField(max_length=30)),
                ('present_address', models.TextField(max_length=1000)),
                ('permanent_address', models.TextField(max_length=1000)),
                ('password', models.CharField(max_length=20)),
                ('re_password', models.CharField(max_length=20)),
            ],
        ),
    ]
