# Generated by Django 4.0.3 on 2022-07-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controller',
            new_name='Admin',
        ),
    ]
