# Generated by Django 4.0.3 on 2022-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='re_password',
        ),
    ]
