# Generated by Django 4.0.3 on 2022-07-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_remove_admin_password_remove_admin_re_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
