# Generated by Django 4.0.3 on 2022-07-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='instation_name',
            field=models.CharField(max_length=100),
        ),
    ]
