# Generated by Django 4.0.3 on 2022-07-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_instation'),
        ('controller', '0004_alter_admin_instation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='instation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.instation'),
        ),
    ]
