# Generated by Django 4.0.3 on 2022-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(max_length=20),
        ),
    ]
