# Generated by Django 4.0.3 on 2022-07-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_admin_instation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='instation_name',
        ),
    ]
