# Generated by Django 4.1 on 2022-08-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Author", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Author",),
    ]
