# Generated by Django 4.0.3 on 2022-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='permanent_address',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='present_address',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
