# Generated by Django 4.0.3 on 2022-08-05 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rootApp', '0005_rename_eni_number_institute_eni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.FileField(upload_to='student/')),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=30)),
                ('present_address', models.TextField(max_length=200)),
                ('permanent_address', models.TextField(max_length=200)),
                ('institute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootApp.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
