# Generated by Django 4.0.3 on 2022-08-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0005_rename_eni_number_institute_eni'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rootApp.status'),
            preserve_default=False,
        ),
    ]
