# Generated by Django 4.1 on 2022-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rootApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("eni", models.CharField(max_length=10)),
                ("address", models.TextField(max_length=150)),
            ],
        ),
    ]
