# Generated by Django 4.1 on 2022-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rootApp", "0002_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institute",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
