# Generated by Django 4.1 on 2022-08-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rootApp", "0003_alter_institute_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institute", old_name="eni", new_name="eni_number",
        ),
    ]
