# Generated by Django 4.1 on 2022-08-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rootApp", "0004_rename_eni_institute_eni_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institute", old_name="eni_number", new_name="eni",
        ),
    ]
