# Generated by Django 4.0.3 on 2022-07-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='student-profile-image/')),
                ('student_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('class_number', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=14)),
                ('email_address', models.CharField(max_length=30)),
                ('present_address', models.TextField(max_length=1000)),
                ('permanent_address', models.TextField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('re_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('present_in_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('payment_in_date', models.DateField()),
                ('payment_amount', models.CharField(max_length=100000)),
                ('payment_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.month')),
            ],
        ),
        migrations.CreateModel(
            name='SingleRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.day')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.subjectname')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('class_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.class')),
            ],
        ),
    ]
