# Generated by Django 4.0.3 on 2022-07-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('payment_in_date', models.DateField()),
                ('payment_month', models.CharField(max_length=15)),
                ('payment_amount', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
