# Generated by Django 4.0.3 on 2022-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='student-profile-image/'),
            preserve_default=False,
        ),
    ]
