# Generated by Django 4.0.3 on 2022-07-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Payments',
            new_name='StudentPayment',
        ),
    ]
