# Generated by Django 4.0.3 on 2022-07-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_admin_instation_name'),
        ('student', '0003_student_password_student_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enter_your_admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.admin'),
        ),
    ]
