# Generated by Django 4.0.3 on 2022-07-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
        ('student', '0005_day_studentroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentroutine',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.day'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
