# Generated by Django 4.0.3 on 2022-07-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_singleroutine'),
        ('student', '0006_alter_studentroutine_day_delete_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentroutine',
            name='day',
        ),
        migrations.AddField(
            model_name='studentroutine',
            name='day',
            field=models.ManyToManyField(to='rootapp.day'),
        ),
    ]
