# Generated by Django 4.0.3 on 2022-07-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_studentroutine_day_studentroutine_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentroutine',
            name='day',
        ),
    ]
