# Generated by Django 4.0.3 on 2022-07-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0006_initial'),
        ('student', '0008_remove_studentroutine_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroutine',
            name='day',
            field=models.ManyToManyField(to='rootapp.day'),
        ),
    ]
