# Generated by Django 4.0.3 on 2022-07-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0009_delete_singleroutine'),
        ('student', '0009_studentroutine_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.day')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.subjectname')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRoutine',
        ),
    ]
