# Generated by Django 4.0.3 on 2022-07-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_examroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamRoutine',
        ),
    ]
