# Generated by Django 4.0.3 on 2022-07-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0010_notice'),
        ('student', '0012_delete_examroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('class_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.class')),
            ],
        ),
    ]
