# Generated by Django 4.0.3 on 2022-07-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0011_month'),
        ('student', '0013_examroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='payment_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.month'),
        ),
    ]
