# Generated by Django 4.0.3 on 2022-07-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_payments_studentpayment'),
        ('student', '0002_student_profile_image'),
        ('student', '0014_alter_studentpayment_payment_month'),
    ]

    operations = [
    ]
