# Generated by Django 4.0.3 on 2022-07-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('day_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.day')),
            ],
        ),
    ]
