# Generated by Django 4.0.3 on 2022-07-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_singleroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='singleroutine',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='singleroutine',
            name='class_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('class_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootapp.class')),
            ],
        ),
    ]
