# Generated by Django 4.0.3 on 2022-07-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleRoutine',
        ),
    ]
