# Generated by Django 4.0.3 on 2022-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0009_delete_singleroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decpritions', models.TextField(max_length=1500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
