# Generated by Django 4.1 on 2022-08-05 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rootApp", "0005_rename_eni_number_institute_eni"),
        ("Student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_number",
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="email_address",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="institute_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rootApp.institute",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address",
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="present_address",
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.FileField(default=1, upload_to="student/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
