# Generated by Django 4.0.3 on 2022-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_class_number_student_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_number',
            field=models.CharField(max_length=10),
        ),
    ]
